-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgosDrLfcbb/LRkpj7
Dj57PQzEv5ec25IKujZYguAfMCSgCgYIKoZIzj0DAQehRANCAATUs3zL4m86YlyI
5oFtjWOkMOqZmLpui4ObA9TNIXx+zgj0yYASsfngwrYssiWRtnpU9RBVyzyWpXKA
Cf9rtDe+
-----END PRIVATE KEY-----