# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "App.xcodeproj")
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_app_store
  end
  desc "Push a new release build to the App Store"
  lane :testflight do
    # key_barear = ENV['GIT_TOKEN']
    # authorization_token_str = ENV['GIT_TOKEN']
    # basic_authorization_token = Base64.strict_encode64(authorization_token_str)
    key_filepath = "private_keys/AuthKey_" + ENV['FASTLANE_KEI_ID'] + ".p8"
    key_id = ENV['FASTLANE_KEI_ID']
    issuer_id = ENV['FASTLANE_ISSUER_ID']
    app_identifier = "mlcity.ru"
    app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_filepath
    )
    sync_code_signing
    # update_code_signing_settings(
    #   use_automatic_signing: false,
    #   bundle_identifier: "mlcity.ru"
    # )
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight(app_identifier: "mlcity.ru")
  end
end
