name: 'MLCityDeploy'

on:
  push:
    branches: ['main', 'android-and-ios-deploy']
  pull_request:
    branches: ['main', 'android-and-ios-deploy']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code```
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Start prettier
        run: npm run prettier:fix

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install androidsdk
        run: sudo snap install androidsdk

      - name: Set path androidsdk
        run: export ANDROID_HOME=$HOME/cmdline-tools && export PATH=$PATH:$ANDROID_HOME/tools/bin && export PATH=$PATH:$ANDROID_HOME/platform-tools

      - name: Install dependencies
        run: npm install

      - name: Build npx
        run: npx ng build --configuration=production && npx cap copy && npx cap sync --inline

      - name: Copy key
        run: cp android/MLCity_key_v2.jks ~/ && chmod ugo+rwx ~/MLCity_key_v2.jks

      - name: Grable build
        if: success()
        run: cd android && sh ./gradlew assembleRelease -Pandroid.injected.signing.store.file=~/MLCity_key_v2.jks -Pandroid.injected.signing.store.password=${{secrets.ANDROID_PASSWORD}} -Pandroid.injected.signing.key.alias=${{secrets.ANDROID_ALIAS}} -Pandroid.injected.signing.key.password=${{secrets.ANDROID_PASSWORD}}
