name: 'Deploy to test server'

on:
  push:
    branches: ['Develop']

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adalave/dev-vokrug-frontend:stable


  re-build-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH }}
          port: ${{ secrets.DEV_SSH_PORT}}


          script: |
            sudo docker stop dev-vokrug-frontend
            sudo docker rm dev-vokrug-frontend
            sudo docker image rm adalave/dev-vokrug-frontend:stable
            docker pull adalave/dev-vokrug-frontend:stable
            docker run -p 80:80 -d --name dev-vokrug-frontend adalave/dev-vokrug-frontend:stable

